version: '3'
services:
  etcd:
    image: bitnami/etcd:latest
    ports:
      - "2379:2379"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    networks:
      - soc

  citus_coordinator:
    image: citusdata/citus:latest
    environment:
      - POSTGRES_DB=soc
      - POSTGRES_USER=soc_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    depends_on:
      - etcd
    networks:
      - soc

  citus_worker_1:
    image: citusdata/citus:latest
    environment:
      - POSTGRES_DB=soc
      - POSTGRES_USER=soc_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    depends_on:
      - etcd
    networks:
      - soc

  citus_worker_2:
    image: citusdata/citus:latest
    environment:
      - POSTGRES_DB=soc
      - POSTGRES_USER=soc_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    depends_on:
      - etcd
    networks:
      - soc

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - soc

  app:
    build:
      context: .
      dockerfile: .docker/dockerfile
    environment:
      DB_HOST: citus_coordinator
      DB_CONNECTION: pgsql
      DB_USER: soc_user
      DB_PASSWORD: password
      DB_NAME: soc
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USER: guest
      RABBIT_PASSWORD: guest
    volumes:
      - ./:/app/soc:delegated
      - ./.docker/entrypoint/soc.sh:/entrypoint.sh:ro
    entrypoint: /entrypoint.sh
    ports:
      - "8080:8080"
    depends_on:
      - citus_coordinator
      - rabbitmq
      - redis
    networks:
      - soc

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    networks:
      - soc

volumes:
  data:
  rabbitmq_data:

networks:
  soc:
