version: '3'
services:
  pg:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: soc_user
      POSTGRES_PASSWORD:
      POSTGRES_DB: soc
      SERVICE_NAME: pg
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INIT_DB_ARGS: "--locale=ru_RU"
      PAGER: less
      TERM: xterm
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql
    networks:
      - soc

 #
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - soc

  app:
    build:
      context: .
      dockerfile: .docker/dockerfile
    environment:
      DB_REPLICA_HOST: pg
      DB_HOST: pg
      DB_CONNECTION: pgsql
      DB_USER: soc_user
      DB_PASSWORD:
      DB_NAME: soc
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBIT_HOST: localhost
      RABBIT_PORT: 5672
      RABBIT_USER: guest
      RABBIT_PASSWORD: guest
    volumes:
      - ./:/app/soc:delegated
      - ./.docker/entrypoint/soc.sh:/entrypoint.sh:ro
    entrypoint: /entrypoint.sh
    ports:
      - "8080:8080"
    depends_on:
      - pg
      - rabbitmq
      - redis
    networks:
      - soc

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    networks:
      - soc

volumes:
  data:
  rabbitmq_data:

networks:
  soc:
