global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: microservices1
    scrape_interval: 10s
    static_configs:
      - targets: ['docker.for.mac.localhost:8081', 'docker.for.mac.localhost:8082']
